services:
  db: 
    image: mysql:8.0
    environment:
      .env_file: .env.example
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - ./Backend/data/init_db.mysql:/docker-entrypoint-initdb.d/init_db.mysql

  backend:
    build: ./Backend
    ports: 
      - "5000:5000"
    environment:
      .env_file: .env.example


  frontend:
    build: ./Frontend
    ports:
      - "5001:5001"
    
volumes:  
  db-data: